// Generated by `formcoach train gate --model cnn` (model/preprocess.json); do not edit.
#pragma once
#define FC_PRE_WINDOW 100
#define FC_PRE_CHANNELS 6
// per-channel mean/std in SI: ax..az m/s^2, gx..gz rad/s
#define FC_PRE_MEAN {-2.513429f, -2.140680f, 1.440121f, -0.026845f, -0.007896f, 0.000116f}
#define FC_PRE_STD {6.865326f, 5.572319f, 4.527741f, 0.960582f, 1.038795f, 1.020460f}
#define FC_INPUT_SCALE 0.16965823f
#define FC_INPUT_ZERO_POINT -21
#define FC_OUTPUT_SCALE 0.00390625f
#define FC_OUTPUT_ZERO_POINT -128
#define FC_N_CLASSES 6
#define FC_CLASS_IDLE 0
#define FC_CLASS_CURL 1
#define FC_CLASS_PRESS 2
#define FC_CLASS_RAISE 3
#define FC_CLASS_SQUAT 4
#define FC_CLASS_OTHER 5
#define FC_MODEL_LEN 16760
