"""int8 post-training quantisation and firmware export (docs/02 §6.3).

``to_tflite_int8`` → full-integer TFLite (int8 in/out) with a representative dataset;
``write_cc`` → ``firmware/model/gate_model_data.cc`` (the ``xxd -i`` form, 16-byte aligned);
``write_preprocess_header`` → ``firmware/model/preprocess.h`` with the standardisation
constants, the quantisation parameters and the class indices; ``tflite_predict`` runs the
quantised model on the laptop so the float → int8 drop can be reported.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from formcoach.models.cnn import Preprocess, _tf


def _converter(model):
    tf = _tf()
    try:
        return tf.lite.TFLiteConverter.from_keras_model(model)
    except Exception:  # Keras 3 models sometimes need a concrete function
        spec = tf.TensorSpec([1, *model.input_shape[1:]], tf.float32)
        fn = tf.function(lambda x: model(x)).get_concrete_function(spec)
        return tf.lite.TFLiteConverter.from_concrete_functions([fn], model)


def to_tflite_int8(model, representative: np.ndarray, out: Path) -> Path:
    """Quantise ``model`` to full-int8 using ``representative`` standardised windows."""
    tf = _tf()
    rep = np.asarray(representative, dtype=np.float32)

    def gen():
        for i in range(len(rep)):
            yield [rep[i : i + 1]]

    conv = _converter(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = gen
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    data = conv.convert()
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(data)
    return out


def to_tflite_float(model, out: Path) -> Path:
    data = _converter(model).convert()
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(data)
    return out


def _interpreter(path: Path):
    tf = _tf()
    try:
        interp = tf.lite.Interpreter(model_path=str(path))
    except AttributeError:  # pragma: no cover - newer TF moved it to ai_edge_litert
        from ai_edge_litert.interpreter import Interpreter

        interp = Interpreter(model_path=str(path))
    interp.allocate_tensors()
    return interp


def quant_params(path: Path) -> dict:
    interp = _interpreter(path)
    i, o = interp.get_input_details()[0], interp.get_output_details()[0]
    return {
        "input_scale": float(i["quantization"][0]),
        "input_zero_point": int(i["quantization"][1]),
        "output_scale": float(o["quantization"][0]),
        "output_zero_point": int(o["quantization"][1]),
        "input_dtype": str(np.dtype(i["dtype"])),
        "input_shape": [int(v) for v in i["shape"]],
    }


def tflite_predict(path: Path, X: np.ndarray) -> np.ndarray:
    """Argmax class indices from the TFLite model for standardised windows ``X``."""
    interp = _interpreter(path)
    i, o = interp.get_input_details()[0], interp.get_output_details()[0]
    scale, zero = i["quantization"]
    out = np.empty(len(X), dtype=np.int64)
    for k in range(len(X)):
        x = np.asarray(X[k : k + 1], dtype=np.float32)
        if i["dtype"] == np.int8:
            x = np.clip(np.round(x / scale + zero), -128, 127).astype(np.int8)
        interp.set_tensor(i["index"], x)
        interp.invoke()
        out[k] = int(np.argmax(interp.get_tensor(o["index"])[0]))
    return out


def write_cc(tflite_path: Path, cc_path: Path, var: str = "gate_model_data") -> Path:
    data = Path(tflite_path).read_bytes()
    lines = [
        "// Generated by `formcoach train gate --model cnn` — do not edit. int8 TFLite flatbuffer.",
        "#include <stddef.h>",
        "",
        f"alignas(16) const unsigned char {var}[] = {{",
    ]
    for k in range(0, len(data), 12):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[k : k + 12]) + ",")
    lines += ["};", f"const size_t {var}_len = {len(data)};", ""]
    cc_path = Path(cc_path)
    cc_path.parent.mkdir(parents=True, exist_ok=True)
    cc_path.write_text("\n".join(lines), encoding="utf-8")
    return cc_path


def write_preprocess_header(pre: Preprocess, classes, path: Path, tflite_path: Path) -> Path:
    q = quant_params(tflite_path)
    fmt = ", ".join
    lines = [
        "// Generated by `formcoach train gate --model cnn` (model/preprocess.json); do not edit.",
        "#pragma once",
        f"#define FC_PRE_WINDOW {pre.window}",
        f"#define FC_PRE_CHANNELS {pre.channels}",
        "// per-channel mean/std in SI: ax..az m/s^2, gx..gz rad/s",
        f"#define FC_PRE_MEAN {{{fmt(f'{v:.6f}f' for v in pre.mean)}}}",
        f"#define FC_PRE_STD {{{fmt(f'{v:.6f}f' for v in pre.std)}}}",
        f"#define FC_INPUT_SCALE {q['input_scale']:.8f}f",
        f"#define FC_INPUT_ZERO_POINT {q['input_zero_point']}",
        f"#define FC_OUTPUT_SCALE {q['output_scale']:.8f}f",
        f"#define FC_OUTPUT_ZERO_POINT {q['output_zero_point']}",
        f"#define FC_N_CLASSES {len(classes)}",
    ]
    for i, c in enumerate(classes):
        lines.append(f"#define FC_CLASS_{c.upper()} {i}")
    lines.append(f"#define FC_MODEL_LEN {Path(tflite_path).stat().st_size}")
    lines.append("")
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
